# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: CPU及核心数
        id: cpu
        run: |
          echo "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          cat /proc/cpuinfo | grep name | cut -f2 -d: >>cpu.info
          cat cpu.info | grep 8272CL
          echo "::set-output name=text::$(cat cpu.info | grep 8272CL)"
      # Runs a set of commands using the runners shell
      - name: 8370C执行区
        if: steps.cpu.outputs.text == ' Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz' && !cancelled()
        
        run: |
          #echo Add other actions to build, Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
          echo test, and deploy your project.
